sudo: false
dist: trusty
language: python
cache: pip
python:
  - "3.6"
before_install:
  - pip install flake8
before_script:
  - flake8 . --count --select=E901,E999,F821,F822,F823 --statistics
  - flake8 . --count --exit-zero --max-line-length=127 --statistics
install:
  - python setup.py install
  - pip install pexpect
script:
  - python dops/tests/test_cli.py
sudo: false